### PR TITLE
Fix redeem computation

### PR DESCRIPTION
**Pull request by dkent600**

### CODE REVIEW

**Comment by orenyodfat** [comment]
> @computedFrom('totalUserReputationEarned', 'totalReputationAvailable')
>   private get percentUserReputationEarned(): string {
>     return this.totalUserReputationEarned.div(this.totalReputationAvailable).mul(100).toFixed(2).toString();
>   }


- does toFixed(2) is a requirements from the ui design team ?  why not give it more precision ?
- does multiple before div might give more accurate results ?

**Comment by dkent600** [comment]
> does toFixed(2) is a requirements from the ui design team ? why not give it more precision ?

I noted this in my feedback on the model II testing.  I expect a spec on this from Alex.

> does multiple before div might give more accurate results ?

When coding this I thought about the same question and decided it was more important to avoid overflow in this calculation than to worry about small precision.  Maybe I'm wrong.  What do you think?

**Comment by orenyodfat** [comment]
> @orenyodfat
> 
> > does toFixed(2) is a requirements from the ui design team ? why not give it more precision ?
> 
> I noted this in my feedback on the model II testing. I expect a spec on this from Alex. Should be in a separate PR.

please open an issue on that
> 
> > does multiple before div might give more accurate results ?
> 
> When coding this I thought about the same question and decided it was more important to avoid overflow in this calculation than to worry about small precision. Maybe I'm wrong. What do you think?

It is dutchX specific so no overflow can happened here

**Comment by dkent600** [comment]
@orenyodfat 
> It is dutchX specific so no overflow can happened here

done:
https://github.com/daostack/dutchx-bootstrapper-ui/pull/33/commits/6c9c6782a529ad58935488f0ea5015516fb25254

**Comment by orenyodfat** [comment]
> @orenyodfat
> 
> > please open an issue on that
> 
> Alex will do what is needed on that

**Pull request merged**
