### PR TITLE
    "webpack-dev-server": "^3.1.14"

### LINKED ISSUE #6: "We found a potential security vulnerability in one of your dependencies."

### PR DESCRIPTION
**Pull request by orenyodfat**
fix #6

### CODE REVIEW

**Comment by dkent600** [comment]
@orenyodfat Have you confirmed that this eliminates all the high security risks?

**Comment by orenyodfat** [comment]
> @orenyodfat Have you confirmed that this eliminates all the high security risks?

Not sure though it want heart. 
https://github.com/webpack/webpack-dev-server/issues/1615

**Comment by dkent600** [comment]
> Not sure though it want heart.

Can you please rephrase?  I don't understand.

**Comment by orenyodfat** [comment]
> > Not sure though it want heart.
> 
> Can you please rephrase? I don't understand.

it solve 3 out of 11 security audit warnings.. 
use `npm audit` for the report

**Comment by dkent600** [comment]
I have already solved this problem 100% in a separate branch.  This PR only does a partial job.

**Pull request closed without merging**
